### PR TITLE
Add encryption of sensitive fields on form submission

### PR DESCRIPTION
**Pull request by bravesirrobin81**

### CODE REVIEW

**Comment by pixie79** [comment]
Why add fetching by ID we never store these as they change

**Comment by pixie79** [comment]
Also we need to not merge any more encryption code until we have agreed how to generate keys, I am going to have to comment out the current key handling as it is blocking deployment to staging as there is no docs on how to create a key

**Comment by bravesirrobin81** [comment]
> Why add fetching by ID we never store these as they change

We need to fetch the schema to figure out what to encrypt. AFAICT the form name isn't submitted, just the id. I would hope the id wouldn't change between loading the form and submitting the data.

**Comment by pixie79** [comment]
Technically yes it can change at the moment yes, in the future less so. Hence why we only use name everywhere as you do have that. As such I would only use name

**Pull request merged**
